onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/aclk}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/aresetn}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awaddr}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awlen}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awsize}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awburst}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awlock}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awcache}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awprot}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awqos}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awregion}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awuser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/awready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/wdata}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/wstrb}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/wlast}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/wuser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/wvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/wready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/bid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/bresp}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/buser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/bvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/bready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/araddr}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arlen}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arsize}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arburst}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arlock}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arcache}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arprot}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arqos}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arregion}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/aruser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/arready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/rid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/rdata}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/rresp}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/rlast}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/ruser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/rvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[0]/rready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/aclk}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/aresetn}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awaddr}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awlen}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awsize}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awburst}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awlock}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awcache}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awprot}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awqos}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awregion}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awuser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/awready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/wdata}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/wstrb}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/wlast}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/wuser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/wvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/wready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/bid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/bresp}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/buser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/bvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/bready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/araddr}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arlen}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arsize}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arburst}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arlock}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arcache}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arprot}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arqos}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arregion}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/aruser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/arready}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/rid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/rdata}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/rresp}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/rlast}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/ruser}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/rvalid}
add wave -noupdate {/axi4_multiport_mem_example/dut_if[1]/rready}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1674642 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 474
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {6229307 ps}
